
################################ Properties ##################################
#server.port=1111
#spring.datasource.url=jdbc:postgresql://localhost:1103/courriers
#spring.datasource.username=postgres
#spring.datasource.password=root
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

################################ YAML ########################################
server:
  port: 1111
spring:
  datasource:
#    url: jdbc:postgresql://localhost:1103/adminapp?createDatabaseIfNotExist=true
    url: jdbc:mysql://localhost:3306/adminapp?createDatabaseIfNotExist=true
#    username: postgres
    username: root
    password:
#    driver-class-name: org.postgresql.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: spring-admin
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        dialect: org.hibernate.dialect.MySQLDialect
#    database: postgresql
#    database: mysql